import { Queue, Worker, type Job } from 'bullmq';
import IORedis from 'ioredis';
import { config } from '../config';
import { sendEmail } from './email';
import { fillRmdFormPdftk } from './pdftk';
import { mapSummaryToRmdFields, extractMedicationFields } from './rmdMapper';
import * as fs from 'fs';

// ---------------------------------------------------------------------------
// Job types
// ---------------------------------------------------------------------------

export type SimpleEmailJob = {
  type: 'simple';
  to: string;
  subject: string;
  html: string;
  text?: string;
};

export type PdfEmailJob = {
  type: 'pdf';
  to: string;
  // Store the summary instead of the Buffer so retries can regenerate the PDF
  // without needing to re-upload a large binary to Redis.
  summary: Record<string, string | boolean | null>;
};

export type EmailJobData = SimpleEmailJob | PdfEmailJob;

// ---------------------------------------------------------------------------
// Connection factory
// BullMQ requires maxRetriesPerRequest: null and takes ownership of the
// connection it receives, so we create a dedicated instance per Queue/Worker.
// ---------------------------------------------------------------------------

function makeConnection(): IORedis {
  return new IORedis(config.redis.url, {
    maxRetriesPerRequest: null,
    enableReadyCheck: false,
  });
}

// ---------------------------------------------------------------------------
// Queue
// ---------------------------------------------------------------------------

export const emailQueue = new Queue<EmailJobData>('marina:email', {
  connection: makeConnection(),
  defaultJobOptions: {
    attempts: 3,
    backoff: {
      type: 'exponential',
      delay: 30_000, // 30 s → 60 s → (job moves to failed)
    },
    removeOnComplete: { count: 100 },
    removeOnFail: { count: 200 },
  },
});

// ---------------------------------------------------------------------------
// Worker factory — call once in index.ts
// ---------------------------------------------------------------------------

export function createEmailWorker(): Worker<EmailJobData> {
  const worker = new Worker<EmailJobData>(
    'marina:email',
    async (job: Job<EmailJobData>) => {
      const { data } = job;

      if (data.type === 'simple') {
        await sendEmail({ to: data.to, subject: data.subject, html: data.html, text: data.text });
        return;
      }

      // pdf — regenerate from summary so no Buffer is stored in Redis
      const medFields = extractMedicationFields(data.summary.currentMedications);
      const rmdFields = mapSummaryToRmdFields({ ...data.summary, ...medFields });

      const outputPath = `/tmp/marina_rmd_q_${job.id}_${Date.now()}.pdf`;
      let pdfBuffer: Buffer;
      try {
        pdfBuffer = await fillRmdFormPdftk(rmdFields, outputPath);
      } finally {
        try { if (fs.existsSync(outputPath)) fs.unlinkSync(outputPath); } catch { /* ignore */ }
      }

      const dateStr = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
      await sendEmail({
        to: data.to,
        subject: 'Your RMD Maritime Medical Report',
        html: `<p>Please find your RMD maritime medical report attached.</p><p>Generated by Marina Health on ${dateStr}.</p>`,
        attachments: [{ filename: 'rmd-maritime-medical-report.pdf', content: pdfBuffer, contentType: 'application/pdf' }],
      });
    },
    {
      connection: makeConnection(),
      concurrency: 2,
    }
  );

  worker.on('completed', (job) => {
    console.log(`[email-queue] job ${job.id} completed (${job.data.type} → ${job.data.to})`);
  });

  worker.on('failed', (job, err) => {
    console.error(
      `[email-queue] job ${job?.id} failed (attempt ${job?.attemptsMade}/${job?.opts.attempts}):`,
      err.message
    );
  });

  return worker;
}

// ---------------------------------------------------------------------------
// Public helpers used by routes
// ---------------------------------------------------------------------------

export async function enqueueEmail(data: SimpleEmailJob): Promise<void> {
  await emailQueue.add('send', data);
}

export async function enqueuePdfEmail(to: string, summary: Record<string, string | boolean | null>): Promise<void> {
  await emailQueue.add('send', { type: 'pdf', to, summary });
}
