// ---------------------------------------------------------------------------
// MarinaWalkthrough — the master composition. Sequences the intro, nine tour
// steps and outro with cross-dissolves, and lays the per-scene voiceover on the
// absolute timeline (audio generated by scripts/gen-vo.mjs → public/audio).
// ---------------------------------------------------------------------------
import React from 'react';
import {
  AbsoluteFill,
  Sequence,
  Audio,
  staticFile,
  useCurrentFrame,
  interpolate,
} from 'remotion';

import {
  FADE,
  INTRO_FRAMES,
  START_FRAMES,
  NOTE_FRAMES,
  LOCATION_FRAMES,
  SETUP_FRAMES,
  STAGES_FRAMES,
  TRANSLATOR_FRAMES,
  REPORT_FRAMES,
  IMPROVE_FRAMES,
  PDF_FRAMES,
  OUTRO_FRAMES,
  VO,
} from './theme';

import { Intro } from './scenes/Intro';
import { Outro } from './scenes/Outro';
import {
  StartScene,
  NoteScene,
  ProfileScene,
  SetupScene,
  StagesScene,
  TranslatorScene,
  ReportScene,
  ImproveScene,
  PdfScene,
} from './scenes/steps';

// Cross-dissolve wrapper — fade + subtle scale at both ends of a scene.
const FadeWrap: React.FC<{ durationInFrames: number; children: React.ReactNode }> = ({
  durationInFrames,
  children,
}) => {
  const frame = useCurrentFrame();
  const opacity = interpolate(
    frame,
    [0, FADE, durationInFrames - FADE, durationInFrames],
    [0, 1, 1, 0],
    { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' }
  );
  const scale = interpolate(
    frame,
    [0, FADE, durationInFrames - FADE, durationInFrames],
    [1.04, 1, 1, 1.04],
    { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' }
  );
  return (
    <AbsoluteFill style={{ opacity, transform: `scale(${scale})`, transformOrigin: 'center' }}>
      {children}
    </AbsoluteFill>
  );
};

// The ordered scene list with its own duration.
const SCENES: { key: string; dur: number; Comp: React.FC }[] = [
  { key: 'intro', dur: INTRO_FRAMES, Comp: Intro },
  { key: 'start', dur: START_FRAMES, Comp: StartScene },
  { key: 'note', dur: NOTE_FRAMES, Comp: NoteScene },
  { key: 'location', dur: LOCATION_FRAMES, Comp: ProfileScene },
  { key: 'setup', dur: SETUP_FRAMES, Comp: SetupScene },
  { key: 'stages', dur: STAGES_FRAMES, Comp: StagesScene },
  { key: 'translator', dur: TRANSLATOR_FRAMES, Comp: TranslatorScene },
  { key: 'report', dur: REPORT_FRAMES, Comp: ReportScene },
  { key: 'improve', dur: IMPROVE_FRAMES, Comp: ImproveScene },
  { key: 'pdf', dur: PDF_FRAMES, Comp: PdfScene },
  { key: 'outro', dur: OUTRO_FRAMES, Comp: Outro },
];

export const MarinaWalkthrough: React.FC = () => {
  // Cumulative start frame of each scene (scenes overlap by FADE for the dissolve).
  let cursor = 0;
  const placed = SCENES.map((s) => {
    const from = cursor;
    cursor += s.dur; // advance by nominal duration; the extra FADE overlaps next
    return { ...s, from };
  });
  const startOf = (key: string) => placed.find((p) => p.key === key)?.from ?? 0;

  return (
    <AbsoluteFill style={{ backgroundColor: '#04263d' }}>
      {/* visuals */}
      {placed.map(({ key, from, dur, Comp }) => (
        <Sequence key={key} from={from} durationInFrames={dur + FADE}>
          <FadeWrap durationInFrames={dur + FADE}>
            <Comp />
          </FadeWrap>
        </Sequence>
      ))}

      {/* voiceover — one clip per scene, offset within the scene for sync */}
      {VO.map((v) => (
        <Sequence
          key={v.name}
          from={startOf(v.scene) + v.from}
          durationInFrames={520}
        >
          <Audio src={staticFile(`audio/${v.name}.mp3`)} volume={1} />
        </Sequence>
      ))}
    </AbsoluteFill>
  );
};
